pub const MIN_LEVERAGE: u8 = 1;
pub const MAX_LEVERAGE: u8 = 5;
pub const BASIS_POINTS: u64 = 10_000;
pub const DEFAULT_INITIAL_MARGIN_BPS: u64 = 2_000; // 20%, equivalent to 5x max leverage.
pub const DEFAULT_MAINTENANCE_MARGIN_BPS: u64 = 625; // 6.25%
pub const DEFAULT_LIQUIDATION_FEE_BPS: u64 = 100;   // 1%
pub const PARTIAL_LIQUIDATION_BPS: u64 = 5_000;     // Close 50% of a position while it still has equity.
pub const DEFAULT_TRADING_FEE_BPS: u64 = 10;        // 0.10%
pub const DEFAULT_MAX_OPEN_INTEREST: u64 = 1_000_000_000_000;
pub const DEFAULT_MAX_SKEW_BPS: u64 = 10_000; // 100%; markets can be tightened after bootstrap.
pub const DEFAULT_MAX_FUNDING_RATE_BPS: u64 = 100;  // Max cumulative funding move per interval.
pub const DEFAULT_FUNDING_INTERVAL_SLOTS: u64 = 1;
pub const MAX_FUNDING_PERIODS_PER_UPDATE: u64 = 24;
pub const DEFAULT_ORACLE_MAX_AGE_SECONDS: u64 = 30;
pub const DEFAULT_ORACLE_MAX_CONFIDENCE_BPS: u64 = 100; // 1%
pub const MAX_STALE_PRICE_SLOTS: u64 = 150; // Roughly one minute on Solana's target slot time.
pub const MAX_PRICE_DECIMALS: u8 = 12;
pub const STARTING_REPUTATION_SCORE: u64 = 100;
pub const PROTOCOL_SEED: &[u8] = b"protocol";
pub const MARKET_SEED: &[u8] = b"market";
pub const TRADER_SEED: &[u8] = b"trader";
pub const MARGIN_SEED: &[u8] = b"margin";
pub const POSITION_SEED: &[u8] = b"position";
pub const VAULT_SEED: &[u8] = b"vault";
